name: "🔀 Pull Request"
description: "Submit changes to the codebase"
title: "PR:"
labels: ["Pull Request"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Description  
        <!-- A clear and concise description of what this pull request does. -->

  - type: checkboxes
    attributes:
      label: "What type of changes does this PR introduce?"
      description: "Select all that apply."
      options:
        - label: "Bug fix (fixes an issue)"
        - label: "Feature (adds a new feature)"
        - label: "Documentation update"
        - label: "Refactor (code improvements without changing functionality)"
        - label: "Other (please specify below)"

  - type: textarea
    attributes:
      label: "Related Issues"
      description: "List any related issues or tickets (e.g., fixes #123)."
      placeholder: "e.g., fixes #123, closes #456"

  - type: textarea
    attributes:
      label: "Proposed Changes"
      description: "Describe the changes made in this pull request."
      value: |
        ## 🔧 Changes Made  
        <!-- List the changes you made in this pull request. -->

  - type: textarea
    attributes:
      label: "Screenshots or Visual Changes (if applicable)"
      description: "Attach screenshots or describe visual changes, if any."
      placeholder: "Drag and drop screenshots here or provide a description."

  - type: input
    attributes:
      label: "Collaborator's GitHub Username (if any)"
      description: "If you collaborated with someone on this pull request, please provide their GitHub username or name."
      placeholder: "@username or Full Name"

  - type: checkboxes
    attributes:
      label: "Checklist"
      options:
        - label: "I have read the contributing guidelines."
          required: true
        - label: "I have added tests that prove my fix is effective or that my feature works."
          required: false
        - label: "I have added necessary documentation (if applicable)."
          required: false
        - label: "Any dependent changes have been merged and published in downstream modules."
          required: false

  - type: markdown
    attributes:
      value: |
        ## 🚀 Thank You!  
        Thank you for your contribution! We will review your pull request as soon as possible.
