name: Auto-Update Project Structure
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  update-structure:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Update project structure
        run: npm run update-structure

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update project structure (auto)"
          branch: main
          skip_fetch: true
          skip_checkout: true
          commit_user_name: "CI Bot"
          commit_author: "ci-bot@example.com"
